title: web-mapping-leaflet
author: Lerry W.S # change this to your name
email:
description: >- # this means to ignore newlines until "baseurl:"
  A template for web-mapping website build in Jekyll + leaflet
baseurl: ""
url: "https://lerryws.xyz/web-mapping-leaflet/" # change this to your url

markdown: kramdown

theme: web-mapping-leaflet

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# exclude : [
#   "Gemfile",
#   "Gemfile.lock",
#   "README.md",
#   "LICENSE.txt",
#   "web-mapping-leaflet.gemspec",
#   ]

css-baseurl:
  - "/assets/css/main.css"

js-baseurl:
  - "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  - "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/js/all.min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.4.1/leaflet.markercluster.js"
  - "/assets/js/Leaflet.fullscreen.min.js"
