title: Jekyll + Leaflet
author: Lerry W.S # change this to your name
email:
description: >- # this means to ignore newlines until "baseurl:"
  Jekyll + leaflet
baseurl: ""
url: ""
port:

# plugins:
#   - jekyll-feed

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "README.md",
  "LICENSE.txt"
  ]
