title: Jekylleaf # Web Mapping Jekyll & Leaflet
author: Lerry William # change this to your name
email:
icon: assets/icons/jekylleaf.png
description: >- # this means to ignore newlines until "baseurl:"
  A template for web-mapping website build in Jekyll + leaflet
baseurl: "/web-mapping-leaflet"
url: "https://lerryws.xyz" # change this to your url

markdown: kramdown

# theme: web-mapping-leaflet

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "README.md",
  "LICENSE.txt",
  "web-mapping-leaflet.gemspec",
  ]