param:
  -
    lat: -0.857
    long: 113.643
    zoom: 5
    minZoom: 2 #minimum zoom level
    maxZoom: 18 #maximum zoom level
    x1:  #longitude lower left
    y1:  #latitude lower left
    x2:  #longitude upper right
    y2:  #latitude upper right
